// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/orchestrator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTestRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TestId                   string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	NumParticipants          int32                  `protobuf:"varint,2,opt,name=num_participants,json=numParticipants,proto3" json:"num_participants,omitempty"`
	Video                    *VideoConfig           `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	Audio                    *AudioConfig           `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	DurationSeconds          int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Spikes                   []*SpikeEvent          `protobuf:"bytes,6,rep,name=spikes,proto3" json:"spikes,omitempty"`
	EnableNetworkDegradation bool                   `protobuf:"varint,7,opt,name=enable_network_degradation,json=enableNetworkDegradation,proto3" json:"enable_network_degradation,omitempty"`
	BackendRtpBasePort       string                 `protobuf:"bytes,8,opt,name=backend_rtp_base_port,json=backendRtpBasePort,proto3" json:"backend_rtp_base_port,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateTestRequest) Reset() {
	*x = CreateTestRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestRequest) ProtoMessage() {}

func (x *CreateTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestRequest.ProtoReflect.Descriptor instead.
func (*CreateTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTestRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *CreateTestRequest) GetNumParticipants() int32 {
	if x != nil {
		return x.NumParticipants
	}
	return 0
}

func (x *CreateTestRequest) GetVideo() *VideoConfig {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *CreateTestRequest) GetAudio() *AudioConfig {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *CreateTestRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *CreateTestRequest) GetSpikes() []*SpikeEvent {
	if x != nil {
		return x.Spikes
	}
	return nil
}

func (x *CreateTestRequest) GetEnableNetworkDegradation() bool {
	if x != nil {
		return x.EnableNetworkDegradation
	}
	return false
}

func (x *CreateTestRequest) GetBackendRtpBasePort() string {
	if x != nil {
		return x.BackendRtpBasePort
	}
	return ""
}

type VideoConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Fps           int32                  `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	BitrateKbps   int32                  `protobuf:"varint,4,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	Codec         string                 `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoConfig) Reset() {
	*x = VideoConfig{}
	mi := &file_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoConfig) ProtoMessage() {}

func (x *VideoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoConfig.ProtoReflect.Descriptor instead.
func (*VideoConfig) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *VideoConfig) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoConfig) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoConfig) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *VideoConfig) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *VideoConfig) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

type AudioConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRate    int32                  `protobuf:"varint,1,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      int32                  `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	BitrateKbps   int32                  `protobuf:"varint,3,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioConfig) Reset() {
	*x = AudioConfig{}
	mi := &file_proto_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioConfig) ProtoMessage() {}

func (x *AudioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioConfig.ProtoReflect.Descriptor instead.
func (*AudioConfig) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *AudioConfig) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioConfig) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioConfig) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *AudioConfig) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

type CreateTestResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TestId           string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Participants     []*ParticipantSetup    `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty"`
	BackendPortStart int32                  `protobuf:"varint,3,opt,name=backend_port_start,json=backendPortStart,proto3" json:"backend_port_start,omitempty"`
	BackendPortEnd   int32                  `protobuf:"varint,4,opt,name=backend_port_end,json=backendPortEnd,proto3" json:"backend_port_end,omitempty"`
	SfuGrpcEndpoint  string                 `protobuf:"bytes,5,opt,name=sfu_grpc_endpoint,json=sfuGrpcEndpoint,proto3" json:"sfu_grpc_endpoint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTestResponse) Reset() {
	*x = CreateTestResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestResponse) ProtoMessage() {}

func (x *CreateTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestResponse.ProtoReflect.Descriptor instead.
func (*CreateTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTestResponse) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *CreateTestResponse) GetParticipants() []*ParticipantSetup {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *CreateTestResponse) GetBackendPortStart() int32 {
	if x != nil {
		return x.BackendPortStart
	}
	return 0
}

func (x *CreateTestResponse) GetBackendPortEnd() int32 {
	if x != nil {
		return x.BackendPortEnd
	}
	return 0
}

func (x *CreateTestResponse) GetSfuGrpcEndpoint() string {
	if x != nil {
		return x.SfuGrpcEndpoint
	}
	return ""
}

type ParticipantSetup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId  uint32                 `protobuf:"varint,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	IceUfrag       string                 `protobuf:"bytes,2,opt,name=ice_ufrag,json=iceUfrag,proto3" json:"ice_ufrag,omitempty"`
	IcePassword    string                 `protobuf:"bytes,3,opt,name=ice_password,json=icePassword,proto3" json:"ice_password,omitempty"`
	SrtpMasterKey  string                 `protobuf:"bytes,4,opt,name=srtp_master_key,json=srtpMasterKey,proto3" json:"srtp_master_key,omitempty"`
	SrtpMasterSalt string                 `protobuf:"bytes,5,opt,name=srtp_master_salt,json=srtpMasterSalt,proto3" json:"srtp_master_salt,omitempty"`
	BackendRtpPort int32                  `protobuf:"varint,6,opt,name=backend_rtp_port,json=backendRtpPort,proto3" json:"backend_rtp_port,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParticipantSetup) Reset() {
	*x = ParticipantSetup{}
	mi := &file_proto_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantSetup) ProtoMessage() {}

func (x *ParticipantSetup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantSetup.ProtoReflect.Descriptor instead.
func (*ParticipantSetup) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *ParticipantSetup) GetParticipantId() uint32 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

func (x *ParticipantSetup) GetIceUfrag() string {
	if x != nil {
		return x.IceUfrag
	}
	return ""
}

func (x *ParticipantSetup) GetIcePassword() string {
	if x != nil {
		return x.IcePassword
	}
	return ""
}

func (x *ParticipantSetup) GetSrtpMasterKey() string {
	if x != nil {
		return x.SrtpMasterKey
	}
	return ""
}

func (x *ParticipantSetup) GetSrtpMasterSalt() string {
	if x != nil {
		return x.SrtpMasterSalt
	}
	return ""
}

func (x *ParticipantSetup) GetBackendRtpPort() int32 {
	if x != nil {
		return x.BackendRtpPort
	}
	return 0
}

type GetSDPOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ParticipantId uint32                 `protobuf:"varint,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSDPOfferRequest) Reset() {
	*x = GetSDPOfferRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSDPOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSDPOfferRequest) ProtoMessage() {}

func (x *GetSDPOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSDPOfferRequest.ProtoReflect.Descriptor instead.
func (*GetSDPOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *GetSDPOfferRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *GetSDPOfferRequest) GetParticipantId() uint32 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

type GetSDPOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSDPOfferResponse) Reset() {
	*x = GetSDPOfferResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSDPOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSDPOfferResponse) ProtoMessage() {}

func (x *GetSDPOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSDPOfferResponse.ProtoReflect.Descriptor instead.
func (*GetSDPOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *GetSDPOfferResponse) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type SetRemoteAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ParticipantId uint32                 `protobuf:"varint,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Sdp           string                 `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRemoteAnswerRequest) Reset() {
	*x = SetRemoteAnswerRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoteAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoteAnswerRequest) ProtoMessage() {}

func (x *SetRemoteAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoteAnswerRequest.ProtoReflect.Descriptor instead.
func (*SetRemoteAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *SetRemoteAnswerRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *SetRemoteAnswerRequest) GetParticipantId() uint32 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

func (x *SetRemoteAnswerRequest) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type SetRemoteAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRemoteAnswerResponse) Reset() {
	*x = SetRemoteAnswerResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoteAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoteAnswerResponse) ProtoMessage() {}

func (x *SetRemoteAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoteAnswerResponse.ProtoReflect.Descriptor instead.
func (*SetRemoteAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *SetRemoteAnswerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetRemoteAnswerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StartTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTestRequest) Reset() {
	*x = StartTestRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestRequest) ProtoMessage() {}

func (x *StartTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestRequest.ProtoReflect.Descriptor instead.
func (*StartTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *StartTestRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

type StartTestResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Started         bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	StartTimeUnixMs int64                  `protobuf:"varint,2,opt,name=start_time_unix_ms,json=startTimeUnixMs,proto3" json:"start_time_unix_ms,omitempty"`
	StatusMessage   string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartTestResponse) Reset() {
	*x = StartTestResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestResponse) ProtoMessage() {}

func (x *StartTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestResponse.ProtoReflect.Descriptor instead.
func (*StartTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *StartTestResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *StartTestResponse) GetStartTimeUnixMs() int64 {
	if x != nil {
		return x.StartTimeUnixMs
	}
	return 0
}

func (x *StartTestResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type SpikeEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SpikeId            string                 `protobuf:"bytes,1,opt,name=spike_id,json=spikeId,proto3" json:"spike_id,omitempty"`
	Type               string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ParticipantIds     []uint32               `protobuf:"varint,3,rep,packed,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	StartOffsetSeconds int32                  `protobuf:"varint,4,opt,name=start_offset_seconds,json=startOffsetSeconds,proto3" json:"start_offset_seconds,omitempty"`
	DurationSeconds    int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Params             map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SpikeEvent) Reset() {
	*x = SpikeEvent{}
	mi := &file_proto_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpikeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpikeEvent) ProtoMessage() {}

func (x *SpikeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpikeEvent.ProtoReflect.Descriptor instead.
func (*SpikeEvent) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *SpikeEvent) GetSpikeId() string {
	if x != nil {
		return x.SpikeId
	}
	return ""
}

func (x *SpikeEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SpikeEvent) GetParticipantIds() []uint32 {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

func (x *SpikeEvent) GetStartOffsetSeconds() int32 {
	if x != nil {
		return x.StartOffsetSeconds
	}
	return 0
}

func (x *SpikeEvent) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *SpikeEvent) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type InjectSpikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Spike         *SpikeEvent            `protobuf:"bytes,2,opt,name=spike,proto3" json:"spike,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectSpikeRequest) Reset() {
	*x = InjectSpikeRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectSpikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectSpikeRequest) ProtoMessage() {}

func (x *InjectSpikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectSpikeRequest.ProtoReflect.Descriptor instead.
func (*InjectSpikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *InjectSpikeRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *InjectSpikeRequest) GetSpike() *SpikeEvent {
	if x != nil {
		return x.Spike
	}
	return nil
}

type InjectSpikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Injected      bool                   `protobuf:"varint,1,opt,name=injected,proto3" json:"injected,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectSpikeResponse) Reset() {
	*x = InjectSpikeResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectSpikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectSpikeResponse) ProtoMessage() {}

func (x *InjectSpikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectSpikeResponse.ProtoReflect.Descriptor instead.
func (*InjectSpikeResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *InjectSpikeResponse) GetInjected() bool {
	if x != nil {
		return x.Injected
	}
	return false
}

func (x *InjectSpikeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *GetMetricsRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

type MetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TestId         string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ElapsedSeconds int64                  `protobuf:"varint,2,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	Participants   []*ParticipantMetrics  `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	Aggregate      *AggregateMetrics      `protobuf:"bytes,4,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *MetricsResponse) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *MetricsResponse) GetElapsedSeconds() int64 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *MetricsResponse) GetParticipants() []*ParticipantMetrics {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *MetricsResponse) GetAggregate() *AggregateMetrics {
	if x != nil {
		return x.Aggregate
	}
	return nil
}

type ParticipantMetrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId        uint32                 `protobuf:"varint,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	FramesSent           int64                  `protobuf:"varint,2,opt,name=frames_sent,json=framesSent,proto3" json:"frames_sent,omitempty"`
	BytesSent            int64                  `protobuf:"varint,3,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	PacketsSent          int64                  `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsRetransmitted int64                  `protobuf:"varint,5,opt,name=packets_retransmitted,json=packetsRetransmitted,proto3" json:"packets_retransmitted,omitempty"`
	JitterMs             float64                `protobuf:"fixed64,6,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	PacketLossPercent    float64                `protobuf:"fixed64,7,opt,name=packet_loss_percent,json=packetLossPercent,proto3" json:"packet_loss_percent,omitempty"`
	NackCount            int64                  `protobuf:"varint,8,opt,name=nack_count,json=nackCount,proto3" json:"nack_count,omitempty"`
	PliCount             int64                  `protobuf:"varint,9,opt,name=pli_count,json=pliCount,proto3" json:"pli_count,omitempty"`
	MosScore             float64                `protobuf:"fixed64,10,opt,name=mos_score,json=mosScore,proto3" json:"mos_score,omitempty"`
	CurrentBitrateKbps   int32                  `protobuf:"varint,11,opt,name=current_bitrate_kbps,json=currentBitrateKbps,proto3" json:"current_bitrate_kbps,omitempty"`
	AvgEncodeLatencyMs   float64                `protobuf:"fixed64,12,opt,name=avg_encode_latency_ms,json=avgEncodeLatencyMs,proto3" json:"avg_encode_latency_ms,omitempty"`
	ActiveSpikeCount     int32                  `protobuf:"varint,13,opt,name=active_spike_count,json=activeSpikeCount,proto3" json:"active_spike_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ParticipantMetrics) Reset() {
	*x = ParticipantMetrics{}
	mi := &file_proto_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantMetrics) ProtoMessage() {}

func (x *ParticipantMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantMetrics.ProtoReflect.Descriptor instead.
func (*ParticipantMetrics) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *ParticipantMetrics) GetParticipantId() uint32 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

func (x *ParticipantMetrics) GetFramesSent() int64 {
	if x != nil {
		return x.FramesSent
	}
	return 0
}

func (x *ParticipantMetrics) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ParticipantMetrics) GetPacketsSent() int64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *ParticipantMetrics) GetPacketsRetransmitted() int64 {
	if x != nil {
		return x.PacketsRetransmitted
	}
	return 0
}

func (x *ParticipantMetrics) GetJitterMs() float64 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *ParticipantMetrics) GetPacketLossPercent() float64 {
	if x != nil {
		return x.PacketLossPercent
	}
	return 0
}

func (x *ParticipantMetrics) GetNackCount() int64 {
	if x != nil {
		return x.NackCount
	}
	return 0
}

func (x *ParticipantMetrics) GetPliCount() int64 {
	if x != nil {
		return x.PliCount
	}
	return 0
}

func (x *ParticipantMetrics) GetMosScore() float64 {
	if x != nil {
		return x.MosScore
	}
	return 0
}

func (x *ParticipantMetrics) GetCurrentBitrateKbps() int32 {
	if x != nil {
		return x.CurrentBitrateKbps
	}
	return 0
}

func (x *ParticipantMetrics) GetAvgEncodeLatencyMs() float64 {
	if x != nil {
		return x.AvgEncodeLatencyMs
	}
	return 0
}

func (x *ParticipantMetrics) GetActiveSpikeCount() int32 {
	if x != nil {
		return x.ActiveSpikeCount
	}
	return 0
}

type AggregateMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalFramesSent  int64                  `protobuf:"varint,1,opt,name=total_frames_sent,json=totalFramesSent,proto3" json:"total_frames_sent,omitempty"`
	TotalPacketsSent int64                  `protobuf:"varint,2,opt,name=total_packets_sent,json=totalPacketsSent,proto3" json:"total_packets_sent,omitempty"`
	AvgJitterMs      float64                `protobuf:"fixed64,3,opt,name=avg_jitter_ms,json=avgJitterMs,proto3" json:"avg_jitter_ms,omitempty"`
	AvgPacketLoss    float64                `protobuf:"fixed64,4,opt,name=avg_packet_loss,json=avgPacketLoss,proto3" json:"avg_packet_loss,omitempty"`
	AvgMosScore      float64                `protobuf:"fixed64,5,opt,name=avg_mos_score,json=avgMosScore,proto3" json:"avg_mos_score,omitempty"`
	TotalBitrateKbps int64                  `protobuf:"varint,6,opt,name=total_bitrate_kbps,json=totalBitrateKbps,proto3" json:"total_bitrate_kbps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AggregateMetrics) Reset() {
	*x = AggregateMetrics{}
	mi := &file_proto_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateMetrics) ProtoMessage() {}

func (x *AggregateMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateMetrics.ProtoReflect.Descriptor instead.
func (*AggregateMetrics) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *AggregateMetrics) GetTotalFramesSent() int64 {
	if x != nil {
		return x.TotalFramesSent
	}
	return 0
}

func (x *AggregateMetrics) GetTotalPacketsSent() int64 {
	if x != nil {
		return x.TotalPacketsSent
	}
	return 0
}

func (x *AggregateMetrics) GetAvgJitterMs() float64 {
	if x != nil {
		return x.AvgJitterMs
	}
	return 0
}

func (x *AggregateMetrics) GetAvgPacketLoss() float64 {
	if x != nil {
		return x.AvgPacketLoss
	}
	return 0
}

func (x *AggregateMetrics) GetAvgMosScore() float64 {
	if x != nil {
		return x.AvgMosScore
	}
	return 0
}

func (x *AggregateMetrics) GetTotalBitrateKbps() int64 {
	if x != nil {
		return x.TotalBitrateKbps
	}
	return 0
}

type StopTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTestRequest) Reset() {
	*x = StopTestRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestRequest) ProtoMessage() {}

func (x *StopTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestRequest.ProtoReflect.Descriptor instead.
func (*StopTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *StopTestRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

type StopTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	FinalMetrics  *MetricsResponse       `protobuf:"bytes,2,opt,name=final_metrics,json=finalMetrics,proto3" json:"final_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTestResponse) Reset() {
	*x = StopTestResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestResponse) ProtoMessage() {}

func (x *StopTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestResponse.ProtoReflect.Descriptor instead.
func (*StopTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{19}
}

func (x *StopTestResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

func (x *StopTestResponse) GetFinalMetrics() *MetricsResponse {
	if x != nil {
		return x.FinalMetrics
	}
	return nil
}

type GetICECandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ParticipantId uint32                 `protobuf:"varint,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetICECandidatesRequest) Reset() {
	*x = GetICECandidatesRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetICECandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetICECandidatesRequest) ProtoMessage() {}

func (x *GetICECandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetICECandidatesRequest.ProtoReflect.Descriptor instead.
func (*GetICECandidatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *GetICECandidatesRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *GetICECandidatesRequest) GetParticipantId() uint32 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

type ICECandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMLineIndex int32                  `protobuf:"varint,3,opt,name=sdp_m_line_index,json=sdpMLineIndex,proto3" json:"sdp_m_line_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICECandidate) Reset() {
	*x = ICECandidate{}
	mi := &file_proto_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidate) ProtoMessage() {}

func (x *ICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidate.ProtoReflect.Descriptor instead.
func (*ICECandidate) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *ICECandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *ICECandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *ICECandidate) GetSdpMLineIndex() int32 {
	if x != nil {
		return x.SdpMLineIndex
	}
	return 0
}

type AddICECandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ParticipantId uint32                 `protobuf:"varint,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Candidate     string                 `protobuf:"bytes,3,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string                 `protobuf:"bytes,4,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMLineIndex int32                  `protobuf:"varint,5,opt,name=sdp_m_line_index,json=sdpMLineIndex,proto3" json:"sdp_m_line_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddICECandidateRequest) Reset() {
	*x = AddICECandidateRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddICECandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddICECandidateRequest) ProtoMessage() {}

func (x *AddICECandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddICECandidateRequest.ProtoReflect.Descriptor instead.
func (*AddICECandidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{22}
}

func (x *AddICECandidateRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *AddICECandidateRequest) GetParticipantId() uint32 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

func (x *AddICECandidateRequest) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *AddICECandidateRequest) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *AddICECandidateRequest) GetSdpMLineIndex() int32 {
	if x != nil {
		return x.SdpMLineIndex
	}
	return 0
}

type AddICECandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         bool                   `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddICECandidateResponse) Reset() {
	*x = AddICECandidateResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddICECandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddICECandidateResponse) ProtoMessage() {}

func (x *AddICECandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddICECandidateResponse.ProtoReflect.Descriptor instead.
func (*AddICECandidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{23}
}

func (x *AddICECandidateResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

func (x *AddICECandidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_orchestrator_proto protoreflect.FileDescriptor

const file_proto_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x18proto/orchestrator.proto\x12\x10udp_simulator.v1\"\x93\x03\n" +
	"\x11CreateTestRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12)\n" +
	"\x10num_participants\x18\x02 \x01(\x05R\x0fnumParticipants\x123\n" +
	"\x05video\x18\x03 \x01(\v2\x1d.udp_simulator.v1.VideoConfigR\x05video\x123\n" +
	"\x05audio\x18\x04 \x01(\v2\x1d.udp_simulator.v1.AudioConfigR\x05audio\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x124\n" +
	"\x06spikes\x18\x06 \x03(\v2\x1c.udp_simulator.v1.SpikeEventR\x06spikes\x12<\n" +
	"\x1aenable_network_degradation\x18\a \x01(\bR\x18enableNetworkDegradation\x121\n" +
	"\x15backend_rtp_base_port\x18\b \x01(\tR\x12backendRtpBasePort\"\x86\x01\n" +
	"\vVideoConfig\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x10\n" +
	"\x03fps\x18\x03 \x01(\x05R\x03fps\x12!\n" +
	"\fbitrate_kbps\x18\x04 \x01(\x05R\vbitrateKbps\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\"\x83\x01\n" +
	"\vAudioConfig\x12\x1f\n" +
	"\vsample_rate\x18\x01 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x02 \x01(\x05R\bchannels\x12!\n" +
	"\fbitrate_kbps\x18\x03 \x01(\x05R\vbitrateKbps\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\"\xf9\x01\n" +
	"\x12CreateTestResponse\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12F\n" +
	"\fparticipants\x18\x02 \x03(\v2\".udp_simulator.v1.ParticipantSetupR\fparticipants\x12,\n" +
	"\x12backend_port_start\x18\x03 \x01(\x05R\x10backendPortStart\x12(\n" +
	"\x10backend_port_end\x18\x04 \x01(\x05R\x0ebackendPortEnd\x12*\n" +
	"\x11sfu_grpc_endpoint\x18\x05 \x01(\tR\x0fsfuGrpcEndpoint\"\xf5\x01\n" +
	"\x10ParticipantSetup\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\rR\rparticipantId\x12\x1b\n" +
	"\tice_ufrag\x18\x02 \x01(\tR\biceUfrag\x12!\n" +
	"\fice_password\x18\x03 \x01(\tR\vicePassword\x12&\n" +
	"\x0fsrtp_master_key\x18\x04 \x01(\tR\rsrtpMasterKey\x12(\n" +
	"\x10srtp_master_salt\x18\x05 \x01(\tR\x0esrtpMasterSalt\x12(\n" +
	"\x10backend_rtp_port\x18\x06 \x01(\x05R\x0ebackendRtpPort\"T\n" +
	"\x12GetSDPOfferRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\rR\rparticipantId\"'\n" +
	"\x13GetSDPOfferResponse\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\"j\n" +
	"\x16SetRemoteAnswerRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\rR\rparticipantId\x12\x10\n" +
	"\x03sdp\x18\x03 \x01(\tR\x03sdp\"X\n" +
	"\x17SetRemoteAnswerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"+\n" +
	"\x10StartTestRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"\x81\x01\n" +
	"\x11StartTestResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12+\n" +
	"\x12start_time_unix_ms\x18\x02 \x01(\x03R\x0fstartTimeUnixMs\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\"\xbe\x02\n" +
	"\n" +
	"SpikeEvent\x12\x19\n" +
	"\bspike_id\x18\x01 \x01(\tR\aspikeId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12'\n" +
	"\x0fparticipant_ids\x18\x03 \x03(\rR\x0eparticipantIds\x120\n" +
	"\x14start_offset_seconds\x18\x04 \x01(\x05R\x12startOffsetSeconds\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12@\n" +
	"\x06params\x18\x06 \x03(\v2(.udp_simulator.v1.SpikeEvent.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x12InjectSpikeRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x122\n" +
	"\x05spike\x18\x02 \x01(\v2\x1c.udp_simulator.v1.SpikeEventR\x05spike\"K\n" +
	"\x13InjectSpikeResponse\x12\x1a\n" +
	"\binjected\x18\x01 \x01(\bR\binjected\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11GetMetricsRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"\xdf\x01\n" +
	"\x0fMetricsResponse\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12'\n" +
	"\x0felapsed_seconds\x18\x02 \x01(\x03R\x0eelapsedSeconds\x12H\n" +
	"\fparticipants\x18\x03 \x03(\v2$.udp_simulator.v1.ParticipantMetricsR\fparticipants\x12@\n" +
	"\taggregate\x18\x04 \x01(\v2\".udp_simulator.v1.AggregateMetricsR\taggregate\"\x8c\x04\n" +
	"\x12ParticipantMetrics\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\rR\rparticipantId\x12\x1f\n" +
	"\vframes_sent\x18\x02 \x01(\x03R\n" +
	"framesSent\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x03 \x01(\x03R\tbytesSent\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x03R\vpacketsSent\x123\n" +
	"\x15packets_retransmitted\x18\x05 \x01(\x03R\x14packetsRetransmitted\x12\x1b\n" +
	"\tjitter_ms\x18\x06 \x01(\x01R\bjitterMs\x12.\n" +
	"\x13packet_loss_percent\x18\a \x01(\x01R\x11packetLossPercent\x12\x1d\n" +
	"\n" +
	"nack_count\x18\b \x01(\x03R\tnackCount\x12\x1b\n" +
	"\tpli_count\x18\t \x01(\x03R\bpliCount\x12\x1b\n" +
	"\tmos_score\x18\n" +
	" \x01(\x01R\bmosScore\x120\n" +
	"\x14current_bitrate_kbps\x18\v \x01(\x05R\x12currentBitrateKbps\x121\n" +
	"\x15avg_encode_latency_ms\x18\f \x01(\x01R\x12avgEncodeLatencyMs\x12,\n" +
	"\x12active_spike_count\x18\r \x01(\x05R\x10activeSpikeCount\"\x8a\x02\n" +
	"\x10AggregateMetrics\x12*\n" +
	"\x11total_frames_sent\x18\x01 \x01(\x03R\x0ftotalFramesSent\x12,\n" +
	"\x12total_packets_sent\x18\x02 \x01(\x03R\x10totalPacketsSent\x12\"\n" +
	"\ravg_jitter_ms\x18\x03 \x01(\x01R\vavgJitterMs\x12&\n" +
	"\x0favg_packet_loss\x18\x04 \x01(\x01R\ravgPacketLoss\x12\"\n" +
	"\ravg_mos_score\x18\x05 \x01(\x01R\vavgMosScore\x12,\n" +
	"\x12total_bitrate_kbps\x18\x06 \x01(\x03R\x10totalBitrateKbps\"*\n" +
	"\x0fStopTestRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"t\n" +
	"\x10StopTestResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\x12F\n" +
	"\rfinal_metrics\x18\x02 \x01(\v2!.udp_simulator.v1.MetricsResponseR\ffinalMetrics\"Y\n" +
	"\x17GetICECandidatesRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\rR\rparticipantId\"n\n" +
	"\fICECandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12'\n" +
	"\x10sdp_m_line_index\x18\x03 \x01(\x05R\rsdpMLineIndex\"\xb8\x01\n" +
	"\x16AddICECandidateRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\rR\rparticipantId\x12\x1c\n" +
	"\tcandidate\x18\x03 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x04 \x01(\tR\x06sdpMid\x12'\n" +
	"\x10sdp_m_line_index\x18\x05 \x01(\x05R\rsdpMLineIndex\"E\n" +
	"\x17AddICECandidateResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\bR\x05added\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xcf\x06\n" +
	"\fOrchestrator\x12W\n" +
	"\n" +
	"CreateTest\x12#.udp_simulator.v1.CreateTestRequest\x1a$.udp_simulator.v1.CreateTestResponse\x12Z\n" +
	"\vGetSDPOffer\x12$.udp_simulator.v1.GetSDPOfferRequest\x1a%.udp_simulator.v1.GetSDPOfferResponse\x12f\n" +
	"\x0fSetRemoteAnswer\x12(.udp_simulator.v1.SetRemoteAnswerRequest\x1a).udp_simulator.v1.SetRemoteAnswerResponse\x12T\n" +
	"\tStartTest\x12\".udp_simulator.v1.StartTestRequest\x1a#.udp_simulator.v1.StartTestResponse\x12Z\n" +
	"\vInjectSpike\x12$.udp_simulator.v1.InjectSpikeRequest\x1a%.udp_simulator.v1.InjectSpikeResponse\x12T\n" +
	"\n" +
	"GetMetrics\x12#.udp_simulator.v1.GetMetricsRequest\x1a!.udp_simulator.v1.MetricsResponse\x12Q\n" +
	"\bStopTest\x12!.udp_simulator.v1.StopTestRequest\x1a\".udp_simulator.v1.StopTestResponse\x12_\n" +
	"\x10GetICECandidates\x12).udp_simulator.v1.GetICECandidatesRequest\x1a\x1e.udp_simulator.v1.ICECandidate0\x01\x12f\n" +
	"\x0fAddICECandidate\x12(.udp_simulator.v1.AddICECandidateRequest\x1a).udp_simulator.v1.AddICECandidateResponseB-Z+github.com/MdSadiqMd/AV-Chaos-Monkey/pkg/pbb\x06proto3"

var (
	file_proto_orchestrator_proto_rawDescOnce sync.Once
	file_proto_orchestrator_proto_rawDescData []byte
)

func file_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestrator_proto_rawDesc), len(file_proto_orchestrator_proto_rawDesc)))
	})
	return file_proto_orchestrator_proto_rawDescData
}

var file_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_orchestrator_proto_goTypes = []any{
	(*CreateTestRequest)(nil),       // 0: udp_simulator.v1.CreateTestRequest
	(*VideoConfig)(nil),             // 1: udp_simulator.v1.VideoConfig
	(*AudioConfig)(nil),             // 2: udp_simulator.v1.AudioConfig
	(*CreateTestResponse)(nil),      // 3: udp_simulator.v1.CreateTestResponse
	(*ParticipantSetup)(nil),        // 4: udp_simulator.v1.ParticipantSetup
	(*GetSDPOfferRequest)(nil),      // 5: udp_simulator.v1.GetSDPOfferRequest
	(*GetSDPOfferResponse)(nil),     // 6: udp_simulator.v1.GetSDPOfferResponse
	(*SetRemoteAnswerRequest)(nil),  // 7: udp_simulator.v1.SetRemoteAnswerRequest
	(*SetRemoteAnswerResponse)(nil), // 8: udp_simulator.v1.SetRemoteAnswerResponse
	(*StartTestRequest)(nil),        // 9: udp_simulator.v1.StartTestRequest
	(*StartTestResponse)(nil),       // 10: udp_simulator.v1.StartTestResponse
	(*SpikeEvent)(nil),              // 11: udp_simulator.v1.SpikeEvent
	(*InjectSpikeRequest)(nil),      // 12: udp_simulator.v1.InjectSpikeRequest
	(*InjectSpikeResponse)(nil),     // 13: udp_simulator.v1.InjectSpikeResponse
	(*GetMetricsRequest)(nil),       // 14: udp_simulator.v1.GetMetricsRequest
	(*MetricsResponse)(nil),         // 15: udp_simulator.v1.MetricsResponse
	(*ParticipantMetrics)(nil),      // 16: udp_simulator.v1.ParticipantMetrics
	(*AggregateMetrics)(nil),        // 17: udp_simulator.v1.AggregateMetrics
	(*StopTestRequest)(nil),         // 18: udp_simulator.v1.StopTestRequest
	(*StopTestResponse)(nil),        // 19: udp_simulator.v1.StopTestResponse
	(*GetICECandidatesRequest)(nil), // 20: udp_simulator.v1.GetICECandidatesRequest
	(*ICECandidate)(nil),            // 21: udp_simulator.v1.ICECandidate
	(*AddICECandidateRequest)(nil),  // 22: udp_simulator.v1.AddICECandidateRequest
	(*AddICECandidateResponse)(nil), // 23: udp_simulator.v1.AddICECandidateResponse
	nil,                             // 24: udp_simulator.v1.SpikeEvent.ParamsEntry
}
var file_proto_orchestrator_proto_depIdxs = []int32{
	1,  // 0: udp_simulator.v1.CreateTestRequest.video:type_name -> udp_simulator.v1.VideoConfig
	2,  // 1: udp_simulator.v1.CreateTestRequest.audio:type_name -> udp_simulator.v1.AudioConfig
	11, // 2: udp_simulator.v1.CreateTestRequest.spikes:type_name -> udp_simulator.v1.SpikeEvent
	4,  // 3: udp_simulator.v1.CreateTestResponse.participants:type_name -> udp_simulator.v1.ParticipantSetup
	24, // 4: udp_simulator.v1.SpikeEvent.params:type_name -> udp_simulator.v1.SpikeEvent.ParamsEntry
	11, // 5: udp_simulator.v1.InjectSpikeRequest.spike:type_name -> udp_simulator.v1.SpikeEvent
	16, // 6: udp_simulator.v1.MetricsResponse.participants:type_name -> udp_simulator.v1.ParticipantMetrics
	17, // 7: udp_simulator.v1.MetricsResponse.aggregate:type_name -> udp_simulator.v1.AggregateMetrics
	15, // 8: udp_simulator.v1.StopTestResponse.final_metrics:type_name -> udp_simulator.v1.MetricsResponse
	0,  // 9: udp_simulator.v1.Orchestrator.CreateTest:input_type -> udp_simulator.v1.CreateTestRequest
	5,  // 10: udp_simulator.v1.Orchestrator.GetSDPOffer:input_type -> udp_simulator.v1.GetSDPOfferRequest
	7,  // 11: udp_simulator.v1.Orchestrator.SetRemoteAnswer:input_type -> udp_simulator.v1.SetRemoteAnswerRequest
	9,  // 12: udp_simulator.v1.Orchestrator.StartTest:input_type -> udp_simulator.v1.StartTestRequest
	12, // 13: udp_simulator.v1.Orchestrator.InjectSpike:input_type -> udp_simulator.v1.InjectSpikeRequest
	14, // 14: udp_simulator.v1.Orchestrator.GetMetrics:input_type -> udp_simulator.v1.GetMetricsRequest
	18, // 15: udp_simulator.v1.Orchestrator.StopTest:input_type -> udp_simulator.v1.StopTestRequest
	20, // 16: udp_simulator.v1.Orchestrator.GetICECandidates:input_type -> udp_simulator.v1.GetICECandidatesRequest
	22, // 17: udp_simulator.v1.Orchestrator.AddICECandidate:input_type -> udp_simulator.v1.AddICECandidateRequest
	3,  // 18: udp_simulator.v1.Orchestrator.CreateTest:output_type -> udp_simulator.v1.CreateTestResponse
	6,  // 19: udp_simulator.v1.Orchestrator.GetSDPOffer:output_type -> udp_simulator.v1.GetSDPOfferResponse
	8,  // 20: udp_simulator.v1.Orchestrator.SetRemoteAnswer:output_type -> udp_simulator.v1.SetRemoteAnswerResponse
	10, // 21: udp_simulator.v1.Orchestrator.StartTest:output_type -> udp_simulator.v1.StartTestResponse
	13, // 22: udp_simulator.v1.Orchestrator.InjectSpike:output_type -> udp_simulator.v1.InjectSpikeResponse
	15, // 23: udp_simulator.v1.Orchestrator.GetMetrics:output_type -> udp_simulator.v1.MetricsResponse
	19, // 24: udp_simulator.v1.Orchestrator.StopTest:output_type -> udp_simulator.v1.StopTestResponse
	21, // 25: udp_simulator.v1.Orchestrator.GetICECandidates:output_type -> udp_simulator.v1.ICECandidate
	23, // 26: udp_simulator.v1.Orchestrator.AddICECandidate:output_type -> udp_simulator.v1.AddICECandidateResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_orchestrator_proto_init() }
func file_proto_orchestrator_proto_init() {
	if File_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestrator_proto_rawDesc), len(file_proto_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_orchestrator_proto_depIdxs,
		MessageInfos:      file_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_orchestrator_proto = out.File
	file_proto_orchestrator_proto_goTypes = nil
	file_proto_orchestrator_proto_depIdxs = nil
}
